# About us UI

AboutUs_ui <- function(){
  tagList(
    bs4Dash::box(status="primary",height = 700,collapsible = FALSE,
            title = h3(strong("Scorecard Overview")), 
            width = 10,
            fluidRow(
              tags$br(),
            div(tags$h5(strong("The Construction Risk Rating Model for Construction etimates the 
            probability of default (PD) of Construction loans by simulating changes in property value, construction cost, and interest rates 
            over time. The model generates probability distributions of the simulated variables by creating 10,000 correlated 
            scenarios."))),
            tags$br(),
            tags$text("Each simulated scenario is parameterized by historical volatiliy to a specific region and property type.
            For each scenario, the simulated property value, construction cost, and interest rate help determine whether a loan
            will default or not based on whether the simulated values drop below a pre-determined threshold. 
            The PD is determined based on the number of default scenarios generated by the simulation."),
            tags$br(),
            tags$text("The drivers of default in the model are loan-to-value (LTV) and cost-to-value (CTV) ratios. 
            Loan-to-value is the ratio of the commitment on the loan to the estimated value of the property at construction completion. 
            Cost-to-value is the ratio of the construction costs to the estimated value of the property at construction 
            completion. The model simulates the paths of property value, construction cost, and interest rate up to the point of the project's completion
            and then determines a one-year PD using the simulated LTV and CTV ratios. If the simulated LTV and CTV drop below the default threshold,
            that scenario is determined to be a default scenario. The risk rating is assigned based on the number of default scenarios generated by the simulation out of 10,000."),
            tags$br(),
            tags$text(em("Note: The CRE Construction Model is designed for use with commercial construction 
            and/or land acquisition and development (LAD) loan structures, 
            where the project is completely sold or refinanced at maturity.")) 
            )
    )
  )
}